/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PayableOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import { FunctionFragment, Result, EventFragment } from "@ethersproject/abi";
import { Listener, Provider } from "@ethersproject/providers";
import { TypedEventFilter, TypedEvent, TypedListener, OnEvent } from "./common";

export interface ExecutorInterface extends utils.Interface {
  functions: {
    "GRACE_PERIOD()": FunctionFragment;
    "MAXIMUM_DELAY()": FunctionFragment;
    "MINIMUM_DELAY()": FunctionFragment;
    "MINIMUM_QUORUM()": FunctionFragment;
    "ONE_HUNDRED_WITH_PRECISION()": FunctionFragment;
    "PROPOSITION_THRESHOLD()": FunctionFragment;
    "VOTE_DIFFERENTIAL()": FunctionFragment;
    "VOTING_DURATION()": FunctionFragment;
    "acceptAdmin()": FunctionFragment;
    "cancelTransaction(address,uint256,string,bytes,uint256,bool)": FunctionFragment;
    "executeTransaction(address,uint256,string,bytes,uint256,bool)": FunctionFragment;
    "getAdmin()": FunctionFragment;
    "getDelay()": FunctionFragment;
    "getMinimumPropositionPowerNeeded(address,uint256)": FunctionFragment;
    "getMinimumVotingPowerNeeded(uint256)": FunctionFragment;
    "getPendingAdmin()": FunctionFragment;
    "isActionQueued(bytes32)": FunctionFragment;
    "isProposalOverGracePeriod(address,uint256)": FunctionFragment;
    "isProposalPassed(address,uint256)": FunctionFragment;
    "isPropositionPowerEnough(address,address,uint256)": FunctionFragment;
    "isQuorumValid(address,uint256)": FunctionFragment;
    "isVoteDifferentialValid(address,uint256)": FunctionFragment;
    "queueTransaction(address,uint256,string,bytes,uint256,bool)": FunctionFragment;
    "setDelay(uint256)": FunctionFragment;
    "setPendingAdmin(address)": FunctionFragment;
    "validateCreatorOfProposal(address,address,uint256)": FunctionFragment;
    "validateProposalCancellation(address,address,uint256)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "GRACE_PERIOD",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MAXIMUM_DELAY",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MINIMUM_DELAY",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MINIMUM_QUORUM",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "ONE_HUNDRED_WITH_PRECISION",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "PROPOSITION_THRESHOLD",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "VOTE_DIFFERENTIAL",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "VOTING_DURATION",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "acceptAdmin",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "cancelTransaction",
    values: [string, BigNumberish, string, BytesLike, BigNumberish, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "executeTransaction",
    values: [string, BigNumberish, string, BytesLike, BigNumberish, boolean]
  ): string;
  encodeFunctionData(functionFragment: "getAdmin", values?: undefined): string;
  encodeFunctionData(functionFragment: "getDelay", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "getMinimumPropositionPowerNeeded",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getMinimumVotingPowerNeeded",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getPendingAdmin",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "isActionQueued",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isProposalOverGracePeriod",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "isProposalPassed",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "isPropositionPowerEnough",
    values: [string, string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "isQuorumValid",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "isVoteDifferentialValid",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "queueTransaction",
    values: [string, BigNumberish, string, BytesLike, BigNumberish, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "setDelay",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setPendingAdmin",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "validateCreatorOfProposal",
    values: [string, string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "validateProposalCancellation",
    values: [string, string, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "GRACE_PERIOD",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MAXIMUM_DELAY",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MINIMUM_DELAY",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MINIMUM_QUORUM",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ONE_HUNDRED_WITH_PRECISION",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "PROPOSITION_THRESHOLD",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "VOTE_DIFFERENTIAL",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "VOTING_DURATION",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "acceptAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "cancelTransaction",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "executeTransaction",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getAdmin", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getDelay", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getMinimumPropositionPowerNeeded",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getMinimumVotingPowerNeeded",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPendingAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isActionQueued",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isProposalOverGracePeriod",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isProposalPassed",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isPropositionPowerEnough",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isQuorumValid",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isVoteDifferentialValid",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "queueTransaction",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setDelay", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setPendingAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "validateCreatorOfProposal",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "validateProposalCancellation",
    data: BytesLike
  ): Result;

  events: {
    "CancelledAction(bytes32,address,uint256,string,bytes,uint256,bool)": EventFragment;
    "ExecutedAction(bytes32,address,uint256,string,bytes,uint256,bool,bytes)": EventFragment;
    "NewAdmin(address)": EventFragment;
    "NewDelay(uint256)": EventFragment;
    "NewPendingAdmin(address)": EventFragment;
    "QueuedAction(bytes32,address,uint256,string,bytes,uint256,bool)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "CancelledAction"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "ExecutedAction"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "NewAdmin"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "NewDelay"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "NewPendingAdmin"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "QueuedAction"): EventFragment;
}

export type CancelledActionEvent = TypedEvent<
  [string, string, BigNumber, string, string, BigNumber, boolean],
  {
    actionHash: string;
    target: string;
    value: BigNumber;
    signature: string;
    data: string;
    executionTime: BigNumber;
    withDelegatecall: boolean;
  }
>;

export type CancelledActionEventFilter = TypedEventFilter<CancelledActionEvent>;

export type ExecutedActionEvent = TypedEvent<
  [string, string, BigNumber, string, string, BigNumber, boolean, string],
  {
    actionHash: string;
    target: string;
    value: BigNumber;
    signature: string;
    data: string;
    executionTime: BigNumber;
    withDelegatecall: boolean;
    resultData: string;
  }
>;

export type ExecutedActionEventFilter = TypedEventFilter<ExecutedActionEvent>;

export type NewAdminEvent = TypedEvent<[string], { newAdmin: string }>;

export type NewAdminEventFilter = TypedEventFilter<NewAdminEvent>;

export type NewDelayEvent = TypedEvent<[BigNumber], { delay: BigNumber }>;

export type NewDelayEventFilter = TypedEventFilter<NewDelayEvent>;

export type NewPendingAdminEvent = TypedEvent<
  [string],
  { newPendingAdmin: string }
>;

export type NewPendingAdminEventFilter = TypedEventFilter<NewPendingAdminEvent>;

export type QueuedActionEvent = TypedEvent<
  [string, string, BigNumber, string, string, BigNumber, boolean],
  {
    actionHash: string;
    target: string;
    value: BigNumber;
    signature: string;
    data: string;
    executionTime: BigNumber;
    withDelegatecall: boolean;
  }
>;

export type QueuedActionEventFilter = TypedEventFilter<QueuedActionEvent>;

export interface Executor extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: ExecutorInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    GRACE_PERIOD(overrides?: CallOverrides): Promise<[BigNumber]>;

    MAXIMUM_DELAY(overrides?: CallOverrides): Promise<[BigNumber]>;

    MINIMUM_DELAY(overrides?: CallOverrides): Promise<[BigNumber]>;

    MINIMUM_QUORUM(overrides?: CallOverrides): Promise<[BigNumber]>;

    ONE_HUNDRED_WITH_PRECISION(overrides?: CallOverrides): Promise<[BigNumber]>;

    PROPOSITION_THRESHOLD(overrides?: CallOverrides): Promise<[BigNumber]>;

    VOTE_DIFFERENTIAL(overrides?: CallOverrides): Promise<[BigNumber]>;

    VOTING_DURATION(overrides?: CallOverrides): Promise<[BigNumber]>;

    acceptAdmin(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    cancelTransaction(
      target: string,
      value: BigNumberish,
      signature: string,
      data: BytesLike,
      executionTime: BigNumberish,
      withDelegatecall: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    executeTransaction(
      target: string,
      value: BigNumberish,
      signature: string,
      data: BytesLike,
      executionTime: BigNumberish,
      withDelegatecall: boolean,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    getAdmin(overrides?: CallOverrides): Promise<[string]>;

    getDelay(overrides?: CallOverrides): Promise<[BigNumber]>;

    getMinimumPropositionPowerNeeded(
      governance: string,
      blockNumber: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    getMinimumVotingPowerNeeded(
      votingSupply: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    getPendingAdmin(overrides?: CallOverrides): Promise<[string]>;

    isActionQueued(
      actionHash: BytesLike,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    isProposalOverGracePeriod(
      governance: string,
      proposalId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    isProposalPassed(
      governance: string,
      proposalId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    isPropositionPowerEnough(
      governance: string,
      user: string,
      blockNumber: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    isQuorumValid(
      governance: string,
      proposalId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    isVoteDifferentialValid(
      governance: string,
      proposalId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    queueTransaction(
      target: string,
      value: BigNumberish,
      signature: string,
      data: BytesLike,
      executionTime: BigNumberish,
      withDelegatecall: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setDelay(
      delay: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setPendingAdmin(
      newPendingAdmin: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    validateCreatorOfProposal(
      governance: string,
      user: string,
      blockNumber: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    validateProposalCancellation(
      governance: string,
      user: string,
      blockNumber: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[boolean]>;
  };

  GRACE_PERIOD(overrides?: CallOverrides): Promise<BigNumber>;

  MAXIMUM_DELAY(overrides?: CallOverrides): Promise<BigNumber>;

  MINIMUM_DELAY(overrides?: CallOverrides): Promise<BigNumber>;

  MINIMUM_QUORUM(overrides?: CallOverrides): Promise<BigNumber>;

  ONE_HUNDRED_WITH_PRECISION(overrides?: CallOverrides): Promise<BigNumber>;

  PROPOSITION_THRESHOLD(overrides?: CallOverrides): Promise<BigNumber>;

  VOTE_DIFFERENTIAL(overrides?: CallOverrides): Promise<BigNumber>;

  VOTING_DURATION(overrides?: CallOverrides): Promise<BigNumber>;

  acceptAdmin(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  cancelTransaction(
    target: string,
    value: BigNumberish,
    signature: string,
    data: BytesLike,
    executionTime: BigNumberish,
    withDelegatecall: boolean,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  executeTransaction(
    target: string,
    value: BigNumberish,
    signature: string,
    data: BytesLike,
    executionTime: BigNumberish,
    withDelegatecall: boolean,
    overrides?: PayableOverrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  getAdmin(overrides?: CallOverrides): Promise<string>;

  getDelay(overrides?: CallOverrides): Promise<BigNumber>;

  getMinimumPropositionPowerNeeded(
    governance: string,
    blockNumber: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  getMinimumVotingPowerNeeded(
    votingSupply: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  getPendingAdmin(overrides?: CallOverrides): Promise<string>;

  isActionQueued(
    actionHash: BytesLike,
    overrides?: CallOverrides
  ): Promise<boolean>;

  isProposalOverGracePeriod(
    governance: string,
    proposalId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<boolean>;

  isProposalPassed(
    governance: string,
    proposalId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<boolean>;

  isPropositionPowerEnough(
    governance: string,
    user: string,
    blockNumber: BigNumberish,
    overrides?: CallOverrides
  ): Promise<boolean>;

  isQuorumValid(
    governance: string,
    proposalId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<boolean>;

  isVoteDifferentialValid(
    governance: string,
    proposalId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<boolean>;

  queueTransaction(
    target: string,
    value: BigNumberish,
    signature: string,
    data: BytesLike,
    executionTime: BigNumberish,
    withDelegatecall: boolean,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setDelay(
    delay: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setPendingAdmin(
    newPendingAdmin: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  validateCreatorOfProposal(
    governance: string,
    user: string,
    blockNumber: BigNumberish,
    overrides?: CallOverrides
  ): Promise<boolean>;

  validateProposalCancellation(
    governance: string,
    user: string,
    blockNumber: BigNumberish,
    overrides?: CallOverrides
  ): Promise<boolean>;

  callStatic: {
    GRACE_PERIOD(overrides?: CallOverrides): Promise<BigNumber>;

    MAXIMUM_DELAY(overrides?: CallOverrides): Promise<BigNumber>;

    MINIMUM_DELAY(overrides?: CallOverrides): Promise<BigNumber>;

    MINIMUM_QUORUM(overrides?: CallOverrides): Promise<BigNumber>;

    ONE_HUNDRED_WITH_PRECISION(overrides?: CallOverrides): Promise<BigNumber>;

    PROPOSITION_THRESHOLD(overrides?: CallOverrides): Promise<BigNumber>;

    VOTE_DIFFERENTIAL(overrides?: CallOverrides): Promise<BigNumber>;

    VOTING_DURATION(overrides?: CallOverrides): Promise<BigNumber>;

    acceptAdmin(overrides?: CallOverrides): Promise<void>;

    cancelTransaction(
      target: string,
      value: BigNumberish,
      signature: string,
      data: BytesLike,
      executionTime: BigNumberish,
      withDelegatecall: boolean,
      overrides?: CallOverrides
    ): Promise<string>;

    executeTransaction(
      target: string,
      value: BigNumberish,
      signature: string,
      data: BytesLike,
      executionTime: BigNumberish,
      withDelegatecall: boolean,
      overrides?: CallOverrides
    ): Promise<string>;

    getAdmin(overrides?: CallOverrides): Promise<string>;

    getDelay(overrides?: CallOverrides): Promise<BigNumber>;

    getMinimumPropositionPowerNeeded(
      governance: string,
      blockNumber: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getMinimumVotingPowerNeeded(
      votingSupply: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getPendingAdmin(overrides?: CallOverrides): Promise<string>;

    isActionQueued(
      actionHash: BytesLike,
      overrides?: CallOverrides
    ): Promise<boolean>;

    isProposalOverGracePeriod(
      governance: string,
      proposalId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<boolean>;

    isProposalPassed(
      governance: string,
      proposalId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<boolean>;

    isPropositionPowerEnough(
      governance: string,
      user: string,
      blockNumber: BigNumberish,
      overrides?: CallOverrides
    ): Promise<boolean>;

    isQuorumValid(
      governance: string,
      proposalId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<boolean>;

    isVoteDifferentialValid(
      governance: string,
      proposalId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<boolean>;

    queueTransaction(
      target: string,
      value: BigNumberish,
      signature: string,
      data: BytesLike,
      executionTime: BigNumberish,
      withDelegatecall: boolean,
      overrides?: CallOverrides
    ): Promise<string>;

    setDelay(delay: BigNumberish, overrides?: CallOverrides): Promise<void>;

    setPendingAdmin(
      newPendingAdmin: string,
      overrides?: CallOverrides
    ): Promise<void>;

    validateCreatorOfProposal(
      governance: string,
      user: string,
      blockNumber: BigNumberish,
      overrides?: CallOverrides
    ): Promise<boolean>;

    validateProposalCancellation(
      governance: string,
      user: string,
      blockNumber: BigNumberish,
      overrides?: CallOverrides
    ): Promise<boolean>;
  };

  filters: {
    "CancelledAction(bytes32,address,uint256,string,bytes,uint256,bool)"(
      actionHash?: null,
      target?: string | null,
      value?: null,
      signature?: null,
      data?: null,
      executionTime?: null,
      withDelegatecall?: null
    ): CancelledActionEventFilter;
    CancelledAction(
      actionHash?: null,
      target?: string | null,
      value?: null,
      signature?: null,
      data?: null,
      executionTime?: null,
      withDelegatecall?: null
    ): CancelledActionEventFilter;

    "ExecutedAction(bytes32,address,uint256,string,bytes,uint256,bool,bytes)"(
      actionHash?: null,
      target?: string | null,
      value?: null,
      signature?: null,
      data?: null,
      executionTime?: null,
      withDelegatecall?: null,
      resultData?: null
    ): ExecutedActionEventFilter;
    ExecutedAction(
      actionHash?: null,
      target?: string | null,
      value?: null,
      signature?: null,
      data?: null,
      executionTime?: null,
      withDelegatecall?: null,
      resultData?: null
    ): ExecutedActionEventFilter;

    "NewAdmin(address)"(newAdmin?: null): NewAdminEventFilter;
    NewAdmin(newAdmin?: null): NewAdminEventFilter;

    "NewDelay(uint256)"(delay?: null): NewDelayEventFilter;
    NewDelay(delay?: null): NewDelayEventFilter;

    "NewPendingAdmin(address)"(
      newPendingAdmin?: null
    ): NewPendingAdminEventFilter;
    NewPendingAdmin(newPendingAdmin?: null): NewPendingAdminEventFilter;

    "QueuedAction(bytes32,address,uint256,string,bytes,uint256,bool)"(
      actionHash?: null,
      target?: string | null,
      value?: null,
      signature?: null,
      data?: null,
      executionTime?: null,
      withDelegatecall?: null
    ): QueuedActionEventFilter;
    QueuedAction(
      actionHash?: null,
      target?: string | null,
      value?: null,
      signature?: null,
      data?: null,
      executionTime?: null,
      withDelegatecall?: null
    ): QueuedActionEventFilter;
  };

  estimateGas: {
    GRACE_PERIOD(overrides?: CallOverrides): Promise<BigNumber>;

    MAXIMUM_DELAY(overrides?: CallOverrides): Promise<BigNumber>;

    MINIMUM_DELAY(overrides?: CallOverrides): Promise<BigNumber>;

    MINIMUM_QUORUM(overrides?: CallOverrides): Promise<BigNumber>;

    ONE_HUNDRED_WITH_PRECISION(overrides?: CallOverrides): Promise<BigNumber>;

    PROPOSITION_THRESHOLD(overrides?: CallOverrides): Promise<BigNumber>;

    VOTE_DIFFERENTIAL(overrides?: CallOverrides): Promise<BigNumber>;

    VOTING_DURATION(overrides?: CallOverrides): Promise<BigNumber>;

    acceptAdmin(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    cancelTransaction(
      target: string,
      value: BigNumberish,
      signature: string,
      data: BytesLike,
      executionTime: BigNumberish,
      withDelegatecall: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    executeTransaction(
      target: string,
      value: BigNumberish,
      signature: string,
      data: BytesLike,
      executionTime: BigNumberish,
      withDelegatecall: boolean,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    getAdmin(overrides?: CallOverrides): Promise<BigNumber>;

    getDelay(overrides?: CallOverrides): Promise<BigNumber>;

    getMinimumPropositionPowerNeeded(
      governance: string,
      blockNumber: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getMinimumVotingPowerNeeded(
      votingSupply: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getPendingAdmin(overrides?: CallOverrides): Promise<BigNumber>;

    isActionQueued(
      actionHash: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    isProposalOverGracePeriod(
      governance: string,
      proposalId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    isProposalPassed(
      governance: string,
      proposalId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    isPropositionPowerEnough(
      governance: string,
      user: string,
      blockNumber: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    isQuorumValid(
      governance: string,
      proposalId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    isVoteDifferentialValid(
      governance: string,
      proposalId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    queueTransaction(
      target: string,
      value: BigNumberish,
      signature: string,
      data: BytesLike,
      executionTime: BigNumberish,
      withDelegatecall: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setDelay(
      delay: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setPendingAdmin(
      newPendingAdmin: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    validateCreatorOfProposal(
      governance: string,
      user: string,
      blockNumber: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    validateProposalCancellation(
      governance: string,
      user: string,
      blockNumber: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    GRACE_PERIOD(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    MAXIMUM_DELAY(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    MINIMUM_DELAY(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    MINIMUM_QUORUM(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    ONE_HUNDRED_WITH_PRECISION(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    PROPOSITION_THRESHOLD(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    VOTE_DIFFERENTIAL(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    VOTING_DURATION(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    acceptAdmin(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    cancelTransaction(
      target: string,
      value: BigNumberish,
      signature: string,
      data: BytesLike,
      executionTime: BigNumberish,
      withDelegatecall: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    executeTransaction(
      target: string,
      value: BigNumberish,
      signature: string,
      data: BytesLike,
      executionTime: BigNumberish,
      withDelegatecall: boolean,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    getAdmin(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getDelay(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getMinimumPropositionPowerNeeded(
      governance: string,
      blockNumber: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getMinimumVotingPowerNeeded(
      votingSupply: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getPendingAdmin(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    isActionQueued(
      actionHash: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    isProposalOverGracePeriod(
      governance: string,
      proposalId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    isProposalPassed(
      governance: string,
      proposalId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    isPropositionPowerEnough(
      governance: string,
      user: string,
      blockNumber: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    isQuorumValid(
      governance: string,
      proposalId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    isVoteDifferentialValid(
      governance: string,
      proposalId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    queueTransaction(
      target: string,
      value: BigNumberish,
      signature: string,
      data: BytesLike,
      executionTime: BigNumberish,
      withDelegatecall: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setDelay(
      delay: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setPendingAdmin(
      newPendingAdmin: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    validateCreatorOfProposal(
      governance: string,
      user: string,
      blockNumber: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    validateProposalCancellation(
      governance: string,
      user: string,
      blockNumber: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
